# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GMT.proto
# Protobuf Python Version: 4.25.0

"""Generated protocol buffer code."""

# Import necessary protobuf modules for handling descriptors and message building
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

# Create a default symbol database used for message registration and lookup
_sym_db = _symbol_database.Default()

# Register and parse the serialized protocol buffer definition from GMT.proto
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tGMT.proto'
    b'\"$\n\x10TimeStampRequest\x12\x10\n\x08\x64ocument\x18\x01 \x01(\x0c'
    b'\"9\n\x11TimeStampResponse\x12\x11\n\tsignature\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t'
    b'2S\n\x10TimeStampService\x12?\n\x14GetDocumentTimeStamp\x12\x11.TimeStampRequest\x1a\x12.TimeStampResponse\"\x00'
    b'\x62\x06proto3'
)

# Bind message and service descriptors to global scope
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GMT_pb2', _globals)

# If not using C-based descriptors, set serialization metadata manually
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_TIMESTAMPREQUEST']._serialized_start = 13     # Start position in byte stream
    _globals['_TIMESTAMPREQUEST']._serialized_end = 49       # End position in byte stream
    _globals['_TIMESTAMPRESPONSE']._serialized_start = 51    # Start position of response message
    _globals['_TIMESTAMPRESPONSE']._serialized_end = 108     # End position of response message
    _globals['_TIMESTAMPSERVICE']._serialized_start = 110    # Start of service definition
    _globals['_TIMESTAMPSERVICE']._serialized_end = 193      # End of service definition

# @@protoc_insertion_point(module_scope)
