# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc  # gRPC module for client-server communication
import GMT_pb2 as GMT__pb2  # Import the generated message classes from GMT.proto


# ============ CLIENT STUB ============

class TimeStampServiceStub(object):
    """
    Client-side stub to call the remote gRPC service.
    This class allows the client to access server methods.
    """

    def __init__(self, channel):
        """
        Initializes the client stub with a gRPC channel.
        
        Args:
            channel: A gRPC Channel object used to communicate with the server.
        """
        # Define the method binding between client and server
        self.GetDocumentTimeStamp = channel.unary_unary(
            '/TimeStampService/GetDocumentTimeStamp',  # Full gRPC method name
            request_serializer=GMT__pb2.TimeStampRequest.SerializeToString,  # Function to serialize request
            response_deserializer=GMT__pb2.TimeStampResponse.FromString,     # Function to deserialize response
        )


# ============ SERVER INTERFACE ============

class TimeStampServiceServicer(object):
    """
    Base class for implementing the server-side of the TimeStampService.
    You must override `GetDocumentTimeStamp` in your server class.
    """

    def GetDocumentTimeStamp(self, request, context):
        """
        This method must be implemented in your server class.

        Args:
            request: A TimeStampRequest message.
            context: Provides RPC-specific information like metadata and error handling.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


# ============ SERVER REGISTRATION ============

def add_TimeStampServiceServicer_to_server(servicer, server):
    """
    Registers the implemented service with a gRPC server.

    Args:
        servicer: An instance of TimeStampServiceServicer with your implementation.
        server: A gRPC server instance.
    """
    rpc_method_handlers = {
        'GetDocumentTimeStamp': grpc.unary_unary_rpc_method_handler(
            servicer.GetDocumentTimeStamp,
            request_deserializer=GMT__pb2.TimeStampRequest.FromString,
            response_serializer=GMT__pb2.TimeStampResponse.SerializeToString,
        ),
    }

    # Add all method handlers to the server
    generic_handler = grpc.method_handlers_generic_handler(
        'TimeStampService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# ============ EXPERIMENTAL API (Optional Use) ============

class TimeStampService(object):
    """
    An experimental API for advanced gRPC interactions (not commonly used in basic projects).
    """

    @staticmethod
    def GetDocumentTimeStamp(request,
                             target,
                             options=(),
                             channel_credentials=None,
                             call_credentials=None,
                             insecure=False,
                             compression=None,
                             wait_for_ready=None,
                             timeout=None,
                             metadata=None):
        """
        Experimental method to invoke GetDocumentTimeStamp using more customizable options.
        Not typically used unless you need custom transports or credentials.
        """
        return grpc.experimental.unary_unary(
            request, target, '/TimeStampService/GetDocumentTimeStamp',
            GMT__pb2.TimeStampRequest.SerializeToString,
            GMT__pb2.TimeStampResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
